name:                 xmonadrc
version:              0.1.0.0
visibility:           public
id:                   xmonadrc-0.1.0.0-inplace
key:                  xmonadrc-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           foko@hetman.com
author:               FokoHetman
category:             Graphics
abi:                  inplace
exposed:              True
exposed-modules:
    Definitions EventHandling Layout StartupHook TrueFullscreen

import-dirs:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/build

library-dirs:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/build

library-dirs-static:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/build

dynamic-library-dirs:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/build

data-dir:             /etc/nixos/assets/xmonad/.
hs-libraries:         HSxmonadrc-0.1.0.0-inplace
depends:
    X11-1.10.3-GAXQvZJvCSD6SGmmQNLulM base-4.19.2.0-f313
    containers-0.6.8-320e directory-1.3.8.5-d38e
    filepath-1.4.301.0-afbe flow-2.0.0.9-9MYV2lhWoCk62Pjr1GIOiJ
    random-1.2.1.3-LsiegnTWRpMKb0MnerGdjW
    xmobar-0.50-5Vf8k9ARNem8jDpHgcZOOO
    xmonad-0.18.0-8kVwJ0trnjGC5BONeCDUcv
    xmonad-contrib-0.18.1-6WJxPxfp5xqGAVHosLSbT2

haddock-interfaces:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/doc/html/xmonadrc/xmonadrc.haddock

haddock-html:
    /etc/nixos/assets/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.8.4/xmonadrc-0.1.0.0/doc/html/xmonadrc
